### ISSUE TITLE
Outdated code in C++ generator breaks the compilation

### ISSUE THREAD

**Issue by huttenlocher** [btc-ag/service-idl#116]
Upon migration to recent CAB Commons versions there are some now invalid parts in C++ generator code, which hinder generated code from being compiled. Most of them are in the ODB project "ExternalDBImpl", but also in case of custom exception types in the IDL; e.g. there is an invalid override: `virtual BTC::Commons::Core::Exception *IntClone() const;`
I have already fixed these problems locally while working on the .NET failable handler support and will provide a pull request for this issue.

**Comment by sigiesec** [comment]
This probably applies when using cpp.servicecomm=0.12 only, right?

**Comment by huttenlocher** [comment]
Good point. Probably yes, I should take care to retain compatibility.

**Comment by sigiesec** [comment]
Yes ;) The integration test runner can run test cases for all target versions.
