### ISSUE TITLE
Allow configuration of generated module names

### ISSUE THREAD

**Issue by sigiesec** [btc-ag/service-idl#164]
For example, instead of using "ServiceAPI", only "API" might be used.

**Comment by sigiesec** [comment]
When using "API" instead of "ServiceAPI", it is no longer clear from the namespace that the contained structs are non-opaque "data transfer objects". In that case, this information should be added to the names of the classes as a suffix, or a subnamepace "DTO" might be used. But maybe it would be better just to stick with "ServiceAPI".

**Comment by kamiddel** [comment]
Meanwhile I am of similar opinion. In respect of the usage, the name ServiceAPI makes sense. ... So, I think there is no need to have a way to configure the namespace to "API".

**Comment by sigiesec** [comment]
Thanks for your response. I am closing the issue consequently.
