### ISSUE TITLE
Allow generation of C++/.NET artifacts as a fragment to be included into an existing CMake-generated solution

### ISSUE THREAD

**Issue by sigiesec** [btc-ag/service-idl#166]
Instead of using the generated conanfile and .NET sln, the generated artifacts should be integrated into an existing CMake-based build that generates a solution containing both the genarated C++/.NET modules as well as other C++/.NET modules.

**Comment by sigiesec** [comment]
This is probably very complex to implement in general. It would be better to build the generated modules separately, i.e. as a separate release unit. The bop-pipelines are currently extended to make this very easy.

**Comment by sigiesec** [comment]
E.g. the OutputDirectory must be configurable in this case, to ensure that the generated projects use the same OutputDirectory as the existing projects.

**Comment by sigiesec** [comment]
Relative paths in the .csproj files must be configurable in this case, since the solution file might be at a different location relative to the .csproj files. This is particularly problematic when including the .csproj files in a cmake project, since the CMake-generated solution may be located at a relative location which is unknown at the time the IDL generator is executed.

**Comment by sigiesec** [comment]
A make.cmakeset files needs to be generated corresponding to each .csproj file.

**Comment by kamiddel** [comment]
From my point of view, the way to get the generated artifacts as an own release unit solves this problem perfectly.

**Comment by sigiesec** [comment]
Thanks for your response. I am closing the issue consequently.
