### ISSUE TITLE
Change output directory of dotnet solutions from dst/AnyCPU/Release bin/Release

### ISSUE THREAD

**Issue by claasd** [btc-ag/service-idl#174]
The output directory `$(SolutionDir)\dst\$(Platform)\$(Configuration)\` was used by BTC before nuget was used as package manager. It should be changed to `$(SolutionDir)\bin\$(Configuration)\`.

**Comment by claasd** [comment]
Yes, as the Platform for pure .NET builds (without Interop/CLI) is always AnyCPU

**Comment by claasd** [comment]
We probably also do not need the Win32 and x64 build options in the csproj files.

**Comment by sigiesec** [comment]
Ok.

**Comment by sigiesec** [comment]
You can test this with version 1.0.0-fix-issue-174-SNAPSHOT
