### ISSUE TITLE
C# generator produces syntactically invalid code

### ISSUE THREAD

**Issue by huttenlocher** [btc-ag/service-idl#18]
In generated C# code there is an issue making the code syntactically invalid, so that the generated project does not compile. In the generated codec file there is a statement `if (plainData === null)` as well as `if (encodedData === null)`; this line was probably introduced while migrating former Xtend code to more recent versions by find-replace ( `===` is the proper way to make a null reference check in Xtend, but this code part is located in a template and finally becomes C# code). I will provide a fix for this.

**Comment by sigiesec** [comment]
Yes, probably this was accidentally introduced in exactly the way you describe.
