### ISSUE TITLE
Add support  for control of ODB-based project generation

### ISSUE THREAD

**Issue by huttenlocher** [btc-ag/service-idl#244]
After implementation of issue #175 there is a need to control generation of ODB-based projects in a flexible way. Currently, the generation is based on a freely chosen heuristic: as soon as a struct contains a member with type "uuid" and name "ID", the ODB-based project "ExternalDBImpl" will be generated. This may be not obvious and not desired by the IDL designer. So a control flag e.g. similar to "-projectSet api/client/server/full-with-skeleton..." must be introduced. By default, the behavior must be "as-is" to preserve integration tests from being broken (= no ODB); by specifying the flag, ODB generation will be triggered according to the previous logic.

**Comment by sigiesec** [comment]
This must be done as part of #175, since otherwise an incompatible change in behaviour would be introduced.
