### ISSUE TITLE
Support external types

### ISSUE THREAD

**Issue by sebastianhaberey** [btc-ag/service-idl#54]
We would like to use an already existing external type in the IDL. In our specific case it's an ID class that belongs to another API and serves to identify objects from that API.

**Comment by sigiesec** [comment]
A general solution for this would significantly increase complexity of both the IDL language and the generators. You would need to model the mapping to types from all target technologies. 

There is builtin support for using a limited set of existing types in the target languages, e.g. strings or integers.

Support for additional specific additional types might be added. Maybe an extension API could also be provided for this.

Could you provide the definition of the type you would like to use? The attributes would still need to be modelled in addition to allow generation of the protobuf definitions.

In general, such a mapping is intended to be done in the manual implementation of the mapper from a generated service API to a predefined OO API. Do you really need to use the existing type in the Service API?

**Comment by sebastianhaberey** [comment]
I guess this is closely related to issue #70 and our wish to work with the generated classes directly. I was not aware that this isn't the intended use when I wrote this ticket here. Still, if working directly with the generated classes became an option, external types would be one of the next logical steps IMO. I can see how technical issues like serialization would be a problem in that case.

**Comment by sigiesec** [comment]
This should be included in a list of FAQs

**Comment by sigiesec** [comment]
NB: For exceptions, this seems to be supported via an ExceptionReferenceDeclaration. However, this doesn't look quite right. I don't understand what should be specified there, and how the mapping for each target technology could be specified.
