### ISSUE TITLE
The directory name of a generated Java module should correspond with its Maven artifactId

### ISSUE THREAD

**Issue by sigiesec** [btc-ag/service-idl#64]

**Comment by sigiesec** [comment]
@GerrietReents @huttenlocher Do you have any concerns that changing this will break your current uses? If yes, I would add the new behaviour as a new option, but retain the existing behaviour. Otherwise, I would just change it.

**Comment by GerrietReents** [comment]
This means having the root directory named like the artifactId in pom file?

**Comment by sigiesec** [comment]
Yes, I meant the artifactId, I changed the description of the issue to reflect this.
