### ISSUE TITLE
Version information should be specified on a larger scope than individual interfaces

### ISSUE THREAD

**Issue by sigiesec** [btc-ag/service-idl#65]
Currently, only interfaces can be versioned. Other definitions within an IDL file are always assigned the default version "0.1.0" by the code generators.

Probably, the possibility to version interfaces individually should be deprecated/removed.

**Comment by GerrietReents** [comment]
Yes, I discovered this as a problem today, too! Maybe we should move to versioning modules.

**Comment by sigiesec** [comment]
Another option is to remove versioning information from the IDL files completely and pass the version as a parameter to the generator.

**Comment by GerrietReents** [comment]
Yes, that would be a good approach. But it should not be (only) a parameter to the generator, but part of a config file, so it could be put under version control together with the idl files.

**Comment by sigiesec** [comment]
I agree, but this is more a general issue that applies to most/all generator parameters. When they are specified in a file, this can also be used when generating from within Eclipse, without the need to add a specific UI for configuration.
