### ISSUE TITLE
Generate OO-API and corresponding mappers along with the Service API

### ISSUE THREAD

**Issue by sebastianhaberey** [btc-ag/service-idl#70]
I know you will probably close this issue right away, but since the other day, when you explained ServiceIDL's concept of the automatically generated Service API vs the manually defined, local OO-API, this didnt leave my head, so I just want to write it down.

Basically, what we subconciously hoped for when we decided to use ServiceIDL was that we would write an IDL, "push the button" and start working with the Java generated entities on the Java side and the C++ generated entities on the other side. We didn't expect that we had to manually write an OO-API to use locally, and the corresponding mapper that maps the OO-API to the Service-API - on both sides.

I'm sure there are convincing technical reasons for having to to this manually, but from a mere user perspective, if I had a magic wand, I'd still love to be able to use the generated entities right away in my code along with my own entities instead of having to map them first.

**Comment by sigiesec** [comment]
As discussed, this is out of scope of the Service IDL. For a limited scope, a Data Modeling DSL (such as that developed by PRINS) could generate both a Service IDL (for all technologies) and technology-specific OO data models, which should probably use a modeling runtime framework such as BTC.CAB.Modeling or EMF4CPP in C++ or EMF in Java.

**Comment by sigiesec** [comment]
This should be included in a list of FAQs.

**Comment by sigiesec** [comment]
@GerrietReents What about moving the PRINS Data Modeling DSL and its Service IDL generator to a new project withing the [BTC GitHub organization](https://github.com/btc-ag/)?

**Comment by GerrietReents** [comment]
Yes, I think we could do this. I'll check this internally.
