### ISSUE TITLE
Set up automated release process

### ISSUE THREAD

**Issue by sigiesec** [btc-ag/service-idl#74]

**Comment by sigiesec** [comment]
https://wiki.eclipse.org/Tycho/Release_Workflow

**Comment by sigiesec** [comment]
@jcoeltjen Can you assist with this?

**Comment by sigiesec** [comment]
@jcoeltjen Can you add the information on the commands to perform a release to this issue?

**Comment by jcoeltjen** [comment]
You can use the changes I made in my fork: https://github.com/jcoeltjen/service-idl/tree/feature/maven-release
As you wished I did not create a PR for this at this point.

You still need to add a repository in `distributionManagement` for stable artifacts.
Then you should be able to create a release with the following commands:

`mvn release:prepare -DreleaseVersion=1.0.0 -DdevelopmentVersion=1.0.1-SNAPSHOT`
and 
`mvn release:perform`

When performing the release you can also pass in a custom list of goals (for example when you don't want to deploy while testing). For this you can use the `-Dgoals="GOAL LIST"` parameter.

**Comment by sigiesec** [comment]
To create a pull request via GitHub API: https://developer.github.com/v3/pulls/?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc#create-a-pull-request
